version: "3"

services:
  api:
    container_name: tv-remote-api
    build:
      context: backend/TvRemote.Api/
      dockerfile: dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9510:8080